version: '3'

services:
  wp:
    image: wordpress:php7.4-fpm-alpine
    container_name: ${PROJECT}_wp
    ports:
        - '9000:9000'
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${PROJECT}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"

      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_AUTH_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_SECURE_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_LOGGED_IN_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_NONCE_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_SECURE_AUTH_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_LOGGED_IN_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      WORDPRESS_NONCE_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb

      # our local dev environment
      WORDPRESS_CONFIG_EXTRA: |

        /* development parameters */
        define('WP_CACHE', false);
        define('ENVIRONMENT', 'local');

        /* configure mail server */
        define('WORDPRESS_SMTP_AUTH', false);
        define('WORDPRESS_SMTP_SECURE', '');
        define('WORDPRESS_SMTP_HOST', 'mailhog');
        define('WORDPRESS_SMTP_PORT', '1025');
        define('WORDPRESS_SMTP_USERNAME', null);
        define('WORDPRESS_SMTP_PASSWORD', null);
        define('WORDPRESS_SMTP_FROM', 'no-reply@wordpress.org');
        define('WORDPRESS_SMTP_FROM_NAME', 'Wordpres Site');

        if(!defined('WP_HOME')) {
          define('WP_HOME', 'http://localhost');
          define('WP_SITEURL', WP_HOME);
        }
    depends_on:
      - db
    links:
      - db
    restart: always
  nginx:
    image: nginx:1.23.1-alpine
    ports:
        - '80:80'
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:rw
        - ./logs/nginx:/var/log/nginx:rw
        - ./wp-app:/var/www/html:rw
    links:
        - wp
    restart: always
  db:
    image: mysql:latest
    container_name: ${PROJECT}_db
    ports:
      - 3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${PROJECT}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  wpcli:
    depends_on: 
      - db
      - wp
    image: wordpress:cli
    links:
      - db
    entrypoint: wp
    command: "--info"
    container_name: ${PROJECT}_wpcli
    volumes:
      - ./wp-app:/var/www/html
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${PROJECT}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT}_phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./mailhog:/maildir

  composer:
    image: composer:latest
    container_name: ${PROJECT}_composer
    volumes:
      - ./wp-app:/var/www/html
    working_dir: /var/www/html/wp-content/themes/${THEME}

volumes:
  db_data:
  wp-app:
